---
- hosts: basicSetUp

  become: yes

  vars:
    ansible_sudo_pass: 'vagrant'

  roles:
    - git
    - vim

- hosts: basicSetUp

  vars:
    dest_dir: '/home/{{ ansible_user }}/projects'

  roles:
    - role: git_checkout
      dest_folder: '{{ dest_dir }}'