---
- hosts: basicSetUp

  become: yes

  vars:
    ansible_sudo_pass: 'vagrant'

  roles:
    - git
    - vim
    - jdk
    - maven

- hosts: basicSetUp

  vars:
    dest_dir: '/home/{{ ansible_user }}'

  roles:
    - role: git_checkout
      dest_folder: '{{ dest_dir }}/projects'

    - role: intellij
      dest_folder: '{{ dest_dir }}/Desktop'